### ISSUE TITLE
E-DistributionMetadata failed (NullPointerException)

### ISSUE THREAD

**Issue by martinnec** [mff-uk/DPUs#100]
![image](https://cloud.githubusercontent.com/assets/4235208/6597009/9fc33128-c7f9-11e4-8df6-b054c1dd85cb.png)

http://uv.opendata.cz/unifiedviews/#!PipelineEdit/162

**Comment by jakubklimek** [comment]
UnifiedViews is deprecated in favor of [LinkedPipes ETL](http://etl.linkedpipes.com)
