### ISSUE TITLE
q-sparqlAsk: Single quotes are removed from the message

### ISSUE THREAD

**Issue by jindrichmynarz** [mff-uk/DPUs#102]
Using e086fdad0a94b00d15fc42ddd3f76536e89e0693 there's a small problem with q-sparqlAsk. When you use an error message containing a single quote, such as "Don't test me!", the quote is removed in the event log (i.e. you will see "Dont test me!"). This may be an issue of the message sanitization, during which the single quote is needlessly removed. However, having discussed this with @skodape, it may be an issue of UnifiedViews/Core instead of this DPU.

**Comment by jakubklimek** [comment]
UnifiedViews is deprecated in favor of [LinkedPipes ETL](http://etl.linkedpipes.com)
