### ISSUE TITLE
Add support for multiple tabs to t-sparqlConstruct, t-sparqlUpdate

### ISSUE THREAD

**Issue by tomas-knap** [mff-uk/DPUs#98]
As part of https://github.com/UnifiedViews/Plugins/issues/92, t-sparql will be denoted as deprecated, and t-sparqlConstruct, t-sparqlUpdate will be used. Nevertheless these DPUs do not support multiple tabs for multiple queries as t-sparql did. 

Goal: To add support for multiple tabs

Motivation: INTLIB pipelines and its compatibility when using t-sparqlConstruct/t-sparqlUpdate

**Comment by jakubklimek** [comment]
Multiple tabs are deprecated. They will not be supported. Use multiple DPUs or merge the SPARQL queries
