### ISSUE TITLE
UK-T-Tabular - cannot process XLSX files

### ISSUE THREAD

**Issue by martinnec** [mff-uk/DPUs#99]
UK-T-Tabular cannot process XLSX files. For example, this one:

http://www.strukturalni-fondy.cz/getmedia/b3b6bd76-d611-4e9e-bd2c-399edf29d690/2015_01-Seznam-prijemcu-(List-of-Beneficiaries)-01_2015.xlsx

I converted it to XLS and it works so there is really a problem with XLSX files.

**Comment by skodape** [comment]
Same problem as with https://github.com/mff-uk/DPUs/issues/90

solution is to update org.apache.po to last version.
